export enum NOTIFICATION_METHODS {
    EMAIL,
    SMS,
    PUSH
}

export enum NOTIFICATION_TEMPLATES {
    USER_EMAIL_VERIFICATION,
    
    SUBSCRIPTION_RENEWAL_SUCCESS,
    SUBSCRIPTION_RENEWAL_CANCEL,
    SUBSCRIPTION_RENEWAL_FAIL,

    IMPORTANT_ANNOUNCE

}